// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230729201507_ALTER_TABLE_PRODUCTOS_ADDFK")]
    partial class ALTER_TABLE_PRODUCTOS_ADDFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Models.BolsilloInteriorModel", b =>
                {
                    b.Property<int>("ID_BolsilloInterior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_BolsilloInterior");

                    b.ToTable("BolsilloInterior");
                });

            modelBuilder.Entity("Domain.Models.CinturaInteriorModel", b =>
                {
                    b.Property<int>("ID_CinturaInterior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_CinturaInterior");

                    b.ToTable("CinturaInterior");
                });

            modelBuilder.Entity("Domain.Models.ClientesModel", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoCliente")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaNac")
                        .HasColumnType("datetime");

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Residencia")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Telefono")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Domain.Models.CollaretaModel", b =>
                {
                    b.Property<int>("ID_Collareta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Collareta");

                    b.ToTable("Collareta");
                });

            modelBuilder.Entity("Domain.Models.DetallePedidosFabricaModel", b =>
                {
                    b.Property<int>("ID_DetallePedidosFabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ID_PedidosFabrica")
                        .HasColumnType("int");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.HasKey("ID_DetallePedidosFabrica");

                    b.HasIndex("ID_PedidosFabrica");

                    b.HasIndex("ID_Producto");

                    b.ToTable("DetallePedidoFabricas");
                });

            modelBuilder.Entity("Domain.Models.DetallePedidosModel", b =>
                {
                    b.Property<int>("ID_DetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.HasKey("ID_DetallePedido");

                    b.HasIndex("ID_Pedido");

                    b.HasIndex("ID_Producto");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("Domain.Models.EmpleadosModel", b =>
                {
                    b.Property<Guid>("ID_Empleados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Legajo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Residencia")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Empleados");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Domain.Models.EstadoPedidoFabricaModel", b =>
                {
                    b.Property<int>("ID_EstadoPedidoFabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_EstadoPedidoFabrica");

                    b.ToTable("EstadoPedidoFabrica");
                });

            modelBuilder.Entity("Domain.Models.EstadoPedidoModel", b =>
                {
                    b.Property<int>("ID_EstadoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_EstadoPedido");

                    b.ToTable("EstadoPedido");
                });

            modelBuilder.Entity("Domain.Models.FacturasModel", b =>
                {
                    b.Property<int>("ID_Factura")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroFactura")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPago")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Factura");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Domain.Models.ForreriaModel", b =>
                {
                    b.Property<int>("ID_Forreria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Forreria");

                    b.ToTable("Forreria");
                });

            modelBuilder.Entity("Domain.Models.HistorialPedidosModel", b =>
                {
                    b.Property<int>("ID_HistorialPedidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ID_EstadoPedido")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.HasKey("ID_HistorialPedidos");

                    b.HasIndex("ID_EstadoPedido");

                    b.HasIndex("ID_Pedido");

                    b.ToTable("HistorialPedidos");
                });

            modelBuilder.Entity("Domain.Models.LazoModel", b =>
                {
                    b.Property<int>("ID_Lazo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Lazo");

                    b.ToTable("Lazo");
                });

            modelBuilder.Entity("Domain.Models.OrdenDeTrabajoFabricaModel", b =>
                {
                    b.Property<int>("ID_OrdenDeTrabajoFabrica")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCerrado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_PedidoFabrica")
                        .HasColumnType("int");

                    b.Property<int>("ID_Sector")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_OrdenDeTrabajoFabrica");

                    b.HasIndex("ID_Sector");

                    b.ToTable("OrdenDeTrabajoFabrica");
                });

            modelBuilder.Entity("Domain.Models.OrdenDeTrabajoModel", b =>
                {
                    b.Property<int>("ID_OrdenDeTrabajo")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCerrado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("ID_Sector")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_OrdenDeTrabajo");

                    b.ToTable("OrdenDeTrabajo");
                });

            modelBuilder.Entity("Domain.Models.PedidosFabricaModel", b =>
                {
                    b.Property<int>("ID_PedidosFabrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalle")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID_Empleados")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ID_EstadoPedidoFabrica")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_PedidosFabrica");

                    b.HasIndex("ID_Empleados");

                    b.HasIndex("ID_EstadoPedidoFabrica");

                    b.ToTable("PedidosFabrica");
                });

            modelBuilder.Entity("Domain.Models.PedidosModel", b =>
                {
                    b.Property<int>("ID_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<Guid>("ID_Empleados")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ID_EstadoPedido")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("int");

                    b.Property<decimal?>("Seña")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Pedido");

                    b.HasIndex("ID_Cliente");

                    b.HasIndex("ID_Empleados");

                    b.HasIndex("ID_EstadoPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Domain.Models.ProductosModel", b =>
                {
                    b.Property<int>("ID_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("CodigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Composicion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ID_BolsilloInterior")
                        .HasColumnType("int");

                    b.Property<int>("ID_CinturaInterior")
                        .HasColumnType("int");

                    b.Property<int>("ID_Collareta")
                        .HasColumnType("int");

                    b.Property<int>("ID_Forreria")
                        .HasColumnType("int");

                    b.Property<int>("ID_Lazo")
                        .HasColumnType("int");

                    b.Property<int>("ID_TelaBase")
                        .HasColumnType("int");

                    b.Property<int>("ID_TelaCombinacion")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoPrenda")
                        .HasColumnType("int");

                    b.Property<int>("ID_Transfer")
                        .HasColumnType("int");

                    b.Property<int>("ID_Vivo")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPrenda")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TallePrenda")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Producto");

                    b.HasIndex("ID_BolsilloInterior");

                    b.HasIndex("ID_CinturaInterior");

                    b.HasIndex("ID_Collareta");

                    b.HasIndex("ID_Forreria");

                    b.HasIndex("ID_Lazo");

                    b.HasIndex("ID_TelaBase");

                    b.HasIndex("ID_TelaCombinacion");

                    b.HasIndex("ID_TipoPrenda");

                    b.HasIndex("ID_Transfer");

                    b.HasIndex("ID_Vivo");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Domain.Models.ProductosProveedorModel", b =>
                {
                    b.Property<int>("ID_ProductoProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CantidadRollos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("ID_Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("MarcaTela")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Precio")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoTela")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_ProductoProveedor");

                    b.HasIndex("ID_Proveedor");

                    b.ToTable("ProductoProveedor");
                });

            modelBuilder.Entity("Domain.Models.ProveedoresModel", b =>
                {
                    b.Property<int>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoProveedor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("datetime2");

                    b.Property<string>("LugarEmpresa")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Proveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("Domain.Models.SectorModel", b =>
                {
                    b.Property<int>("ID_Sector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NombreSector")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Sector");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("Domain.Models.TelaBaseModel", b =>
                {
                    b.Property<int>("ID_TelaBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_TelaBase");

                    b.ToTable("TelaBase");
                });

            modelBuilder.Entity("Domain.Models.TelaCombinacionModel", b =>
                {
                    b.Property<int>("ID_TelaCombinacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_TelaCombinacion");

                    b.ToTable("TelaCombinacion");
                });

            modelBuilder.Entity("Domain.Models.TipoPrendaModel", b =>
                {
                    b.Property<int>("ID_TipoPrenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TipoPrenda")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_TipoPrenda");

                    b.ToTable("TipoPrenda");
                });

            modelBuilder.Entity("Domain.Models.TransferModel", b =>
                {
                    b.Property<int>("ID_Transfer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Transfer");

                    b.ToTable("Transfer");
                });

            modelBuilder.Entity("Domain.Models.VentasModel", b =>
                {
                    b.Property<int>("ID_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CapitalRecibido")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Venta");

                    b.HasIndex("ID_Producto");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("Domain.Models.VivoModel", b =>
                {
                    b.Property<int>("ID_Vivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_Vivo");

                    b.ToTable("Vivo");
                });

            modelBuilder.Entity("Domain.Models.DetallePedidosFabricaModel", b =>
                {
                    b.HasOne("Domain.Models.PedidosFabricaModel", "PedidosFabrica")
                        .WithMany("DetallePedidosFabrica")
                        .HasForeignKey("ID_PedidosFabrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.ProductosModel", "Producto")
                        .WithMany("DetallePedidosFabrica")
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidosFabrica");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Models.DetallePedidosModel", b =>
                {
                    b.HasOne("Domain.Models.PedidosModel", "Pedidos")
                        .WithMany("DetallePedido")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.ProductosModel", "Producto")
                        .WithMany("DetallePedido")
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedidos");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Models.FacturasModel", b =>
                {
                    b.HasOne("Domain.Models.PedidosModel", "Pedidos")
                        .WithMany("Factura")
                        .HasForeignKey("ID_Factura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Domain.Models.HistorialPedidosModel", b =>
                {
                    b.HasOne("Domain.Models.EstadoPedidoModel", "EstadoPedido")
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("ID_EstadoPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.PedidosModel", "Pedidos")
                        .WithMany("HistorialPedidos")
                        .HasForeignKey("ID_Pedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPedido");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Domain.Models.OrdenDeTrabajoFabricaModel", b =>
                {
                    b.HasOne("Domain.Models.PedidosFabricaModel", "PedidosFabrica")
                        .WithMany("OrdenDeTrabajoFabrica")
                        .HasForeignKey("ID_OrdenDeTrabajoFabrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.SectorModel", "Sector")
                        .WithMany("OrdenDeTrabajoFabrica")
                        .HasForeignKey("ID_Sector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidosFabrica");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Models.OrdenDeTrabajoModel", b =>
                {
                    b.HasOne("Domain.Models.PedidosModel", "Pedidos")
                        .WithMany("OrdenDeTrabajo")
                        .HasForeignKey("ID_OrdenDeTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.SectorModel", "Sector")
                        .WithMany("OrdenDeTrabajo")
                        .HasForeignKey("ID_OrdenDeTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedidos");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Models.PedidosFabricaModel", b =>
                {
                    b.HasOne("Domain.Models.EmpleadosModel", "Empleados")
                        .WithMany("PedidosFabrica")
                        .HasForeignKey("ID_Empleados")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.EstadoPedidoFabricaModel", "EstadoPedidoFabrica")
                        .WithMany("PedidosFabrica")
                        .HasForeignKey("ID_EstadoPedidoFabrica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("EstadoPedidoFabrica");
                });

            modelBuilder.Entity("Domain.Models.PedidosModel", b =>
                {
                    b.HasOne("Domain.Models.ClientesModel", "Clientes")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.EmpleadosModel", "Empleados")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_Empleados")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.EstadoPedidoModel", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("ID_EstadoPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("EstadoPedido");
                });

            modelBuilder.Entity("Domain.Models.ProductosModel", b =>
                {
                    b.HasOne("Domain.Models.BolsilloInteriorModel", "BolsilloInterior")
                        .WithMany()
                        .HasForeignKey("ID_BolsilloInterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.CinturaInteriorModel", "CinturaInterior")
                        .WithMany()
                        .HasForeignKey("ID_CinturaInterior")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.CollaretaModel", "Collareta")
                        .WithMany()
                        .HasForeignKey("ID_Collareta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.ForreriaModel", "Forreria")
                        .WithMany()
                        .HasForeignKey("ID_Forreria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.LazoModel", "Lazo")
                        .WithMany()
                        .HasForeignKey("ID_Lazo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TelaBaseModel", "TelaBase")
                        .WithMany()
                        .HasForeignKey("ID_TelaBase")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TelaCombinacionModel", "TelaCombinacion")
                        .WithMany()
                        .HasForeignKey("ID_TelaCombinacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TipoPrendaModel", "TipoPrenda")
                        .WithMany()
                        .HasForeignKey("ID_TipoPrenda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.TransferModel", "Transfer")
                        .WithMany()
                        .HasForeignKey("ID_Transfer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.VivoModel", "Vivo")
                        .WithMany()
                        .HasForeignKey("ID_Vivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BolsilloInterior");

                    b.Navigation("CinturaInterior");

                    b.Navigation("Collareta");

                    b.Navigation("Forreria");

                    b.Navigation("Lazo");

                    b.Navigation("TelaBase");

                    b.Navigation("TelaCombinacion");

                    b.Navigation("TipoPrenda");

                    b.Navigation("Transfer");

                    b.Navigation("Vivo");
                });

            modelBuilder.Entity("Domain.Models.ProductosProveedorModel", b =>
                {
                    b.HasOne("Domain.Models.ProveedoresModel", "Proveedor")
                        .WithMany("ProductoProveedor")
                        .HasForeignKey("ID_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Domain.Models.VentasModel", b =>
                {
                    b.HasOne("Domain.Models.ProductosModel", "Producto")
                        .WithMany("Venta")
                        .HasForeignKey("ID_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Domain.Models.ClientesModel", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Domain.Models.EmpleadosModel", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("PedidosFabrica");
                });

            modelBuilder.Entity("Domain.Models.EstadoPedidoFabricaModel", b =>
                {
                    b.Navigation("PedidosFabrica");
                });

            modelBuilder.Entity("Domain.Models.EstadoPedidoModel", b =>
                {
                    b.Navigation("HistorialPedidos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Domain.Models.PedidosFabricaModel", b =>
                {
                    b.Navigation("DetallePedidosFabrica");

                    b.Navigation("OrdenDeTrabajoFabrica");
                });

            modelBuilder.Entity("Domain.Models.PedidosModel", b =>
                {
                    b.Navigation("DetallePedido");

                    b.Navigation("Factura");

                    b.Navigation("HistorialPedidos");

                    b.Navigation("OrdenDeTrabajo");
                });

            modelBuilder.Entity("Domain.Models.ProductosModel", b =>
                {
                    b.Navigation("DetallePedido");

                    b.Navigation("DetallePedidosFabrica");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Domain.Models.ProveedoresModel", b =>
                {
                    b.Navigation("ProductoProveedor");
                });

            modelBuilder.Entity("Domain.Models.SectorModel", b =>
                {
                    b.Navigation("OrdenDeTrabajo");

                    b.Navigation("OrdenDeTrabajoFabrica");
                });
#pragma warning restore 612, 618
        }
    }
}
